apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daeemon-pod 
  namespace: dev 
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: daemon-container
        image: httpd 
