apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-pod
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd

